# -*- coding: utf-8 -*-
"""
/***************************************************************************
 ColorLayer
                                 A QGIS plugin
 Colors the selected layer
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2018-11-12
        copyright            : (C) 2018 by jonah
        email                : jonah@jonah.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load ColorLayer class from file ColorLayer.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .color_layer import ColorLayer
    return ColorLayer(iface)
